### ISSUE TITLE
How do I set topic mode(Pub/Sub) or queue mode(P2P) use by AmqpClient?

### ISSUE THREAD

**Issue by HongZhaoHua** [vert-x3/vertx-amqp-client#27]
### Questions

How do I set topic mode(Pub/Sub) or queue mode(P2P) use by AmqpClient?

### Version

VertX 3.8.5
Artemis 2.11.0

### Steps to reproduce

**1. Here is my source code, it created 1 producer and 5 consumer:** 
public class VertxAmqpTestCase {

    private static final String content = "message";

    @Test
    public void test() throws Exception {
        ProtonConnection c;
        Vertx vertx = Vertx.vertx();
        AmqpClientOptions options = new AmqpClientOptions().setHost("localhost").setPort(5672);
        AmqpClient client = AmqpClient.create(vertx, options);

        client.connect((connect) -> {
            if (connect.succeeded()) {
                AmqpConnection connection = connect.result();
                connection.createSender("amqp-queue", (send) -> {
                    for (int index = 0; index < 5; index++) {
                        int id = index;
                        connection.createReceiver("amqp-queue", (receive) -> {
                            AmqpReceiver receiver = receive.result();
                            receiver.handler((message) -> {
                                System.out.println(id + "_" + message.address());
                                Assert.assertEquals("amqp-queue", message.address());
                                Assert.assertEquals(content, message.bodyAsString());
                            });
                        });
                    }

                    AmqpSender sender = send.result();
                    AmqpMessageBuilder builder = AmqpMessage.create();
                    builder.withBody(content);
                    AmqpMessage message = builder.build();
                    sender.send(message);
                });
            } else {
                Assert.fail();
            }
        });

        Thread.sleep(5000);

        client.close((close) -> {
            vertx.close();
        });
    }

}

**2. it always print out as follow:**
0_amqp-queue
1_amqp-queue
4_amqp-queue
2_amqp-queue
3_amqp-queue

**3. it means it work by topic mode(Pub/Sub).**
So, How do I set AmqpClient to queue mode?

**Comment by sebthom** [comment]
I had the same question and peeked at the source code of the [qpid-jms-client](https://github.com/apache/qpid-jms/tree/master/qpid-jms-client) and based on that came up with:

```java
AmqpReceiverOptions opts = new AmqpReceiverOptions()
  .addCapability("queue")
  .setQos(ProtonQoS.AT_MOST_ONCE.name());

connection.createReceiver("amqp-queue", opts, (completionEvent) -> {
  AmqpReceiver receiver = completionEvent.result();
  receiver.handler((message) -> {
    System.out.println(id + "_" + message.address());
    Assert.assertEquals("amqp-queue", message.address());
    Assert.assertEquals(content, message.bodyAsString());
   });
});
```

**Comment by vietj** [comment]
should we document this ?

**Comment by gemmellr** [comment]
The base AMQP 1.0 spec  is essentially P2P and deals with transferring messages between 'nodes' A and B, it does not care what the nodes are, or define how to create them, or specific e.g. queue/topic behaviours, which is why there isnt an explicit 'queue mode' or 'topic mode' for example.

The behaviour seen against a specific server is mostly down to the server, not the client. ActiveMQ Artemis defaults to auto-creating its own address+queue entities when a sender and receiver links attaches and/or send messages. Its configuration defaults to creating 'multicast addresses queues', i.e essentially giving topic behaviour by default. It can be configured to auto-create 'anycast addresses and queues' instead, giving queue behaviour. E.g see "Auto Address Creation" at http://activemq.apache.org/components/artemis/documentation/latest/address-model.html. Or if you know you need particular queues etc, you can pre configure them. This is all independent of the client, which just indicates the AMQP address it is attaching to.

As noticed, Qpid JMS does add particular 'capabilities' to the source/target terminus details when creating [fixed-address] senders and receivers, e.g "queue" or "topic", depending on the type of Destination object given. It does this since JMS does define particular destination types and behaviours, and it is placed there mostly as a hint should particular server peers decide to auto-create things (JMS also does not deal with creation generally, other than implying it doesnt automatically happen). Artemis does look for these terminus capabilities, and so they can be used to hint and possibly tailor its behaviour somewhat.

I probably wouldnt document this much since its server specific, maybe just a note saying 'for some servers you can e.g pass a terminus capability in the sender or receiver options [one-line example of creating options]'. I certainly wouldnt document it using an 'at most once' receiver as relatively few should use those, particularly with a queue (more typical usage would be with a topic model).
